wip

diff --git a/modules/qutebrowser/userscripts/1pass b/modules/qutebrowser/userscripts/1pass
--- a/modules/qutebrowser/userscripts/1pass
+++ b/modules/qutebrowser/userscripts/1pass
@@ -1,68 +1,5 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-set +e
-
-# JS field injection code from https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/password_fill
-javascript_escape() {
-    # print the first argument in an escaped way, such that it can safely
-    # be used within javascripts double quotes
-    # shellcheck disable=SC2001
-    sed "s,[\\\\'\"\/],\\\\&,g" <<< "$1"
-}
-
-js() {
-cat <<EOF
-    function isVisible(elem) {
-        var style = elem.ownerDocument.defaultView.getComputedStyle(elem, null);
-        if (style.getPropertyValue("visibility") !== "visible" ||
-            style.getPropertyValue("display") === "none" ||
-            style.getPropertyValue("opacity") === "0") {
-            return false;
-        }
-        return elem.offsetWidth > 0 && elem.offsetHeight > 0;
-    };
-    function hasPasswordField(form) {
-        var inputs = form.getElementsByTagName("input");
-        for (var j = 0; j < inputs.length; j++) {
-            var input = inputs[j];
-            if (input.type == "password") {
-                return true;
-            }
-        }
-        return false;
-    };
-    function loadData2Form (form) {
-        var inputs = form.getElementsByTagName("input");
-        for (var j = 0; j < inputs.length; j++) {
-            var input = inputs[j];
-            if (isVisible(input) && (input.type == "text" || input.type == "email")) {
-                input.focus();
-                input.value = "$(javascript_escape "${USERNAME}")";
-                input.dispatchEvent(new Event('change'));
-                input.blur();
-            }
-            if (input.type == "password") {
-                input.focus();
-                input.value = "$(javascript_escape "${PASSWORD}")";
-                input.dispatchEvent(new Event('change'));
-                input.blur();
-            }
-        }
-    };
-    var forms = document.getElementsByTagName("form");
-    if("$(javascript_escape "${QUTE_URL}")" == window.location.href) {
-        for (i = 0; i < forms.length; i++) {
-            if (hasPasswordField(forms[i])) {
-                loadData2Form(forms[i]);
-            }
-        }
-    } else {
-        alert("Secrets will not be inserted.\nUrl of this page and the one where the user script was started differ.");
-    }
-EOF
-}
-
-URL=$(echo "$QUTE_URL" | awk -F/ '{print $3}' | sed 's/www.//g')
 TOKEN_TMPDIR="${TMPDIR:-/tmp}"
 TOKEN_CACHE="$TOKEN_TMPDIR/1pass.token"
 
@@ -133,15 +70,29 @@ fi
 echo "message-info 'Looking for password for $URL...'" >> "$QUTE_FIFO"
 
 JQ_TITLE_EXPR='.title + " (in vault \"" + .vault.name + "\")"'
+    
+accounts=$(op accounts list --format json | jq -r '.[].shorthand')
+echo $(echo $accounts | wc -w)
+echo $accounts
+if [[ $(echo $accounts | wc -w) -gt 1 ]]; then
+    ACCOUNT=$(echo "$accounts" | dmenu-prompt "Select account") || ACCOUNT=""
+else
+    ACCOUNT="$accounts"
+fi
+
+if [ -z "$ACCOUNT" ]; then
+    echo "message-error 'No account picked.'" >> "$QUTE_FIFO"
+    exit 1
+fi
 
 if [ -f "$TOKEN_CACHE" ]; then
     TOKEN="$(cat "$TOKEN_CACHE")"
     if ! op signin --raw --session="$TOKEN" > /dev/null; then
-        TOKEN="$(dmenu-prompt-pass "1password: "| op signin --raw)" || TOKEN=""
+        TOKEN="$(dmenu-prompt-pass "1password password: "| op signin --raw --account $ACCOUNT)" || TOKEN=""
         echo "$TOKEN" > "$TOKEN_CACHE"
     fi
 else
-    TOKEN=$(dmenu-prompt-pass "1password: "| op signin --raw) || TOKEN=""
+    TOKEN=$(dmenu-prompt-pass "1password password: "| op signin --raw --account $ACCOUNT) || TOKEN=""
     install -m 600 /dev/null "$TOKEN_CACHE"
     echo "$TOKEN" > "$TOKEN_CACHE"
 fi
